---

- hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: create user sione
      tags: always
      user:
        name: simone
        groups: root

    - name: add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH3yjZ+MKWnKaEy9TfDIjJZCEsLJvJx2UZZD7FCDgQTC ansible ssh key"
    
    - name: add sudoers file for simone
      copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: 0440
