---

- hosts: all
  become: true
  tasks:
    - name: install apache2 package
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes

    - name: open firewall for httpd
      ansible.posix.firewalld:
        port: 80/tcp
        zone: public
        permanent: "yes"
        state: enabled
        immediate: yes
      when: ansible_distribution == "RedHat"

    - name: start httpd services on RedHat
      ansible.builtin.service:
        name: httpd
        state: started
      become: true
      when: ansible_distribution == "RedHat"
